volumes:
  db_data:

x-shared_environment: &shared_environment
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_PORT: ${DATABASE_PORT}
  CONTAINER_PORT: ${CONTAINER_PORT}
  USERNAME: ${USERNAME}
  PASSWORD: ${PASSWORD}

services:
  app:
    volumes:
      - ./:/app/
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${CONTAINER_PORT}:${CONTAINER_PORT}'
    restart: always
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USERNAME -d $DATABASE_NAME"]
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    restart: always
