x-shared_environment: &shared_environment
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_PORT: ${DATABASE_PORT}
  CONTAINER_PORT: ${CONTAINER_PORT}
  USERNAME: ${USERNAME}
  PASSWORD: ${PASSWORD}

services:
  app:
    volumes:
      - ./:/app/
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '${CONTAINER_PORT}:${CONTAINER_PORT}'
    restart: always
